"""
Autonomous Fund — AI Fund Manager
===================================
Orchestrates all three layers into a single autonomous trading fund:

Layer 1: Alpha Genome → Evolves novel strategies
Layer 2: Liquidation Oracle → Predicts forced-seller cascades
Layer 3: Fund Manager → Risk, execution, verification, performance

Every decision is:
- Generated by evolved strategies or liquidation signals
- Validated by the risk manager
- Executed via the execution engine
- Recorded in the verifiable ledger (hash-chained)
- Tracked with full performance attribution
"""

import logging
import time
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import pandas as pd

from src.alpha_genome.gene import tree_from_dict, tree_hash, tree_to_formula
from src.alpha_genome.evolution import EvolvedStrategy
from src.alpha_genome.decay import DecayDetector
from src.liquidation.oracle import LiquidationOracle, LiquidationSignal
from src.risk.manager import RiskManager, RiskLimits, PositionRequest
from src.risk.adaptive_kelly import AdaptiveKellySizer
from src.fund.ledger import VerifiableLedger
from src.fund.performance import PerformanceEngine
from src.fund.health import HealthMonitor

logger = logging.getLogger(__name__)


@dataclass
class FundState:
    """Current state of the autonomous fund."""
    capital: float
    peak_capital: float
    total_pnl: float
    total_return_pct: float
    drawdown_pct: float
    open_positions: dict
    active_strategies: int
    liquidation_risk_score: float
    ledger_entries: int
    ledger_verified: bool
    is_halted: bool
    halt_reason: str = ""


@dataclass
class StrategyAllocation:
    """Capital allocation to a strategy."""
    strategy_name: str
    strategy_type: str        # "alpha_genome" or "liquidation"
    allocation_pct: float     # % of capital allocated
    active: bool
    performance: dict = field(default_factory=dict)


class AutonomousFundManager:
    """The AI fund manager that ties everything together.

    Decision flow:
    1. Load evolved strategies (Alpha Genome) + liquidation signals
    2. For each signal source, generate candidate trades
    3. Risk manager approves/rejects each trade
    4. Approved trades are executed and logged to verifiable ledger
    5. Performance tracked with full strategy attribution
    """

    def __init__(
        self,
        initial_capital: float = 10000,
        risk_limits: Optional[RiskLimits] = None,
        max_strategies: int = 10,
        rebalance_interval_hours: int = 24,
        ledger_path: str = "fund_data/ledger.json",
        decay_kill_threshold: float = 70.0,
        kelly_max_fraction: float = 0.04,
        health_report_path: str = "fund_data/health.json",
    ):
        self.initial_capital = initial_capital
        self.current_capital = initial_capital
        self.max_strategies = max_strategies
        self.rebalance_hours = rebalance_interval_hours

        # Core components
        self.risk_manager = RiskManager(
            capital=initial_capital,
            limits=risk_limits or RiskLimits(),
        )
        self.ledger = VerifiableLedger(ledger_path=ledger_path)
        self.liquidation_oracle = LiquidationOracle()

        # New components: decay detection, adaptive sizing, attribution, health
        self.decay_detector = DecayDetector(
            decay_score_kill_threshold=decay_kill_threshold,
        )
        self.kelly_sizer = AdaptiveKellySizer(
            max_fraction=kelly_max_fraction,
        )
        self.performance_engine = PerformanceEngine()
        self.health_monitor = HealthMonitor(
            health_report_path=health_report_path,
        )

        # Strategy portfolio
        self.active_strategies: list[EvolvedStrategy] = []
        self.strategy_allocations: dict[str, StrategyAllocation] = {}
        self.open_positions: dict[str, dict] = {}

        # Performance tracking
        self.strategy_pnl: dict[str, float] = {}
        self._last_rebalance = 0.0

    def load_strategies(self, strategies: list[EvolvedStrategy]):
        """Load evolved strategies into the fund and register with all subsystems."""
        # Rank by fitness and take top N
        ranked = sorted(
            strategies, key=lambda s: s.fitness.fitness, reverse=True
        )[:self.max_strategies]

        self.active_strategies = ranked

        # Equal-weight allocation initially
        n = len(ranked)
        if n == 0:
            return

        per_strategy_pct = 0.8 / n  # Reserve 20% as cash buffer

        for strat in ranked:
            self.strategy_allocations[strat.name] = StrategyAllocation(
                strategy_name=strat.name,
                strategy_type="alpha_genome",
                allocation_pct=per_strategy_pct,
                active=True,
            )
            self.strategy_pnl.setdefault(strat.name, 0.0)

            # Register with new subsystems
            self.decay_detector.register_strategy(strat.name, self.initial_capital)
            self.kelly_sizer.register_strategy(strat.name, self.initial_capital)
            self.performance_engine.register_strategy(strat.name, "alpha_genome")
            self.health_monitor.update_strategy_health(strat.name, "active")

        # Reserve allocation for liquidation signals
        self.strategy_allocations["liquidation_oracle"] = StrategyAllocation(
            strategy_name="liquidation_oracle",
            strategy_type="liquidation",
            allocation_pct=0.15,
            active=True,
        )
        self.strategy_pnl.setdefault("liquidation_oracle", 0.0)
        self.decay_detector.register_strategy("liquidation_oracle", self.initial_capital)
        self.kelly_sizer.register_strategy("liquidation_oracle", self.initial_capital)
        self.performance_engine.register_strategy("liquidation_oracle", "liquidation")

        logger.info(
            f"Fund loaded {n} evolved strategies + liquidation oracle. "
            f"Total allocation: {sum(a.allocation_pct for a in self.strategy_allocations.values()):.0%}"
        )

    def generate_signals(
        self, df: pd.DataFrame, asset: str, current_price: float
    ) -> list[dict]:
        """Generate all trading signals from all sources.

        Returns a list of candidate trades, each tagged with its source.
        """
        candidates = []

        # 1. Alpha Genome signals
        for strat in self.active_strategies:
            alloc = self.strategy_allocations.get(strat.name)
            if not alloc or not alloc.active:
                continue

            try:
                tree = tree_from_dict(strat.tree_dict)
                signals = tree.evaluate(df)
                current_signal = float(signals.iloc[-1]) if len(signals) > 0 else 0

                if current_signal != 0:
                    direction = 1 if current_signal > 0 else -1
                    atr = df["atr_14"].iloc[-1] if "atr_14" in df.columns else current_price * 0.02

                    candidates.append({
                        "source": "alpha_genome",
                        "strategy_name": strat.name,
                        "strategy_hash": strat.tree_hash,
                        "asset": asset,
                        "direction": direction,
                        "price": current_price,
                        "stop_loss": current_price - direction * 2 * atr,
                        "take_profit": current_price + direction * 3 * atr,
                        "signal_strength": min(1.0, strat.fitness.oos_sharpe / 3.0),
                        "allocation_pct": alloc.allocation_pct,
                        "reasoning": f"Evolved strategy {strat.name}: {strat.formula[:80]}",
                    })
            except Exception as e:
                logger.error(f"Error evaluating strategy {strat.name}: {e}")

        # 2. Liquidation Oracle signals
        try:
            liq_signals = self.liquidation_oracle.generate_signals(
                asset, current_price
            )
            liq_alloc = self.strategy_allocations.get("liquidation_oracle")
            alloc_pct = liq_alloc.allocation_pct if liq_alloc else 0.1

            for lsig in liq_signals:
                candidates.append({
                    "source": "liquidation_oracle",
                    "strategy_name": f"liq_{lsig.signal_type}",
                    "strategy_hash": "liquidation_oracle",
                    "asset": lsig.asset,
                    "direction": lsig.direction,
                    "price": lsig.entry_price,
                    "stop_loss": lsig.stop_loss,
                    "take_profit": lsig.target_price,
                    "signal_strength": lsig.confidence,
                    "allocation_pct": alloc_pct,
                    "reasoning": lsig.reasoning,
                })
        except Exception as e:
            logger.error(f"Liquidation oracle error: {e}")

        return candidates

    def process_signals(
        self, candidates: list[dict]
    ) -> list[dict]:
        """Process candidate trades through risk management + Kelly sizing.

        Each candidate is evaluated by the risk manager and sized via
        adaptive Kelly. Approved trades are logged to the verifiable ledger.
        """
        approved = []

        # Get Kelly sizes for all strategies at once
        strategy_names = [c["strategy_name"] for c in candidates]
        signal_strengths = {c["strategy_name"]: c["signal_strength"] for c in candidates}
        peak_capital = max(self.current_capital, self.initial_capital)

        kelly_sizes = self.kelly_sizer.compute_portfolio_size(
            strategy_names=list(set(strategy_names)),
            signal_strengths=signal_strengths,
            current_capital=self.current_capital,
            peak_capital=peak_capital,
        )

        for candidate in candidates:
            # Skip if already in a position for this asset
            if candidate["asset"] in self.open_positions:
                continue

            # Check if strategy is decaying — skip if kill recommended
            kill_list = self.decay_detector.get_kill_list()
            if candidate["strategy_name"] in kill_list:
                logger.warning(
                    f"Skipping signal from {candidate['strategy_name']}: "
                    f"decay detector recommends kill"
                )
                self.health_monitor.update_strategy_health(
                    candidate["strategy_name"], "decaying"
                )
                continue

            # Kelly-adjusted position size
            kelly_result = kelly_sizes.get(candidate["strategy_name"])
            kelly_fraction = kelly_result.fraction if kelly_result else 0.02

            # Build risk request
            request = PositionRequest(
                symbol=candidate["asset"],
                direction=candidate["direction"],
                entry_price=candidate["price"],
                stop_loss=candidate["stop_loss"],
                take_profit=candidate["take_profit"],
                signal_name=candidate["strategy_name"],
                signal_strength=candidate["signal_strength"],
            )

            approval = self.risk_manager.evaluate(request)

            # Log to verifiable ledger regardless of approval
            self.ledger.append(
                entry_type="signal",
                asset=candidate["asset"],
                direction=candidate["direction"],
                price=candidate["price"],
                size=approval.size if approval.approved else 0,
                strategy_name=candidate["strategy_name"],
                strategy_hash=candidate["strategy_hash"],
                signal_strength=candidate["signal_strength"],
                risk_approval=approval.approved,
                risk_details=approval.reason,
                metadata={
                    "source": candidate["source"],
                    "reasoning": candidate["reasoning"],
                    "kelly_fraction": kelly_fraction,
                    "kelly_reason": kelly_result.reason if kelly_result else "no_stats",
                },
            )

            if approval.approved:
                # Use Kelly-adjusted size (capped by risk manager)
                kelly_size = kelly_fraction * self.current_capital / candidate["price"]
                final_size = min(approval.size, kelly_size) if kelly_size > 0 else approval.size
                candidate["approved_size"] = final_size
                candidate["risk_pct"] = approval.risk_pct
                candidate["kelly_fraction"] = kelly_fraction
                approved.append(candidate)

        return approved

    def execute_trades(
        self, approved: list[dict], execution_engine
    ) -> list[dict]:
        """Execute approved trades and record in ledger + health monitor."""
        executed = []

        for trade in approved:
            result = execution_engine.execute_entry(
                symbol=trade["asset"],
                direction=trade["direction"],
                size=trade["approved_size"],
                stop_loss=trade["stop_loss"],
                take_profit=trade["take_profit"],
            )

            # Record execution quality for health monitoring
            self.health_monitor.record_execution(
                symbol=trade["asset"],
                expected_price=trade["price"],
                actual_price=result.price if result.success else trade["price"],
                success=result.success,
                error="" if result.success else "execution_failed",
            )
            result = execution_engine.execute_entry(
                symbol=trade["asset"],
                direction=trade["direction"],
                size=trade["approved_size"],
                stop_loss=trade["stop_loss"],
                take_profit=trade["take_profit"],
            )

            if result.success:
                # Record in ledger
                self.ledger.append(
                    entry_type="trade_open",
                    asset=trade["asset"],
                    direction=trade["direction"],
                    price=result.price,
                    size=trade["approved_size"],
                    strategy_name=trade["strategy_name"],
                    strategy_hash=trade["strategy_hash"],
                    signal_strength=trade["signal_strength"],
                    risk_approval=True,
                    risk_details=f"Executed. Risk={trade['risk_pct']:.1%}",
                )

                # Track open position
                self.open_positions[trade["asset"]] = {
                    "direction": trade["direction"],
                    "size": trade["approved_size"],
                    "entry_price": result.price,
                    "strategy_name": trade["strategy_name"],
                    "strategy_hash": trade["strategy_hash"],
                    "signal_strength": trade["signal_strength"],
                    "stop_loss": trade["stop_loss"],
                    "take_profit": trade["take_profit"],
                    "opened_at": time.time(),
                }

                self.risk_manager.register_open(
                    trade["asset"], trade["direction"],
                    trade["approved_size"], result.price,
                )

                executed.append(trade)

        return executed

    def check_exits(self, current_prices: dict, execution_engine) -> list[dict]:
        """Check if any open positions need to be closed."""
        closed = []

        for asset, pos in list(self.open_positions.items()):
            price = current_prices.get(asset)
            if price is None:
                continue

            should_close = False
            close_reason = ""

            # Stop loss
            if pos["direction"] == 1 and price <= pos["stop_loss"]:
                should_close = True
                close_reason = "stop_loss"
            elif pos["direction"] == -1 and price >= pos["stop_loss"]:
                should_close = True
                close_reason = "stop_loss"

            # Take profit
            if pos["direction"] == 1 and price >= pos["take_profit"]:
                should_close = True
                close_reason = "take_profit"
            elif pos["direction"] == -1 and price <= pos["take_profit"]:
                should_close = True
                close_reason = "take_profit"

            if should_close:
                result = execution_engine.execute_exit(
                    asset, pos["size"], pos["direction"]
                )

                if result.success:
                    # Compute PnL
                    if pos["direction"] == 1:
                        pnl = (result.price - pos["entry_price"]) * pos["size"]
                    else:
                        pnl = (pos["entry_price"] - result.price) * pos["size"]

                    # Record in ledger
                    self.ledger.append(
                        entry_type="trade_close",
                        asset=asset,
                        direction=pos["direction"],
                        price=result.price,
                        size=pos["size"],
                        strategy_name=pos["strategy_name"],
                        strategy_hash=pos["strategy_hash"],
                        signal_strength=pos["signal_strength"],
                        risk_approval=True,
                        risk_details=close_reason,
                        pnl=pnl,
                    )

                    # Update tracking
                    self.strategy_pnl[pos["strategy_name"]] = (
                        self.strategy_pnl.get(pos["strategy_name"], 0) + pnl
                    )
                    self.current_capital += pnl
                    self.risk_manager.register_close(asset, result.price)
                    del self.open_positions[asset]

                    # Feed trade result to all subsystems
                    return_pct = pnl / (pos["entry_price"] * pos["size"]) if pos["size"] > 0 else 0
                    self.decay_detector.record_trade(pos["strategy_name"], pnl)
                    self.kelly_sizer.record_trade(pos["strategy_name"], pnl, return_pct)
                    self.performance_engine.record_trade(
                        strategy_name=pos["strategy_name"],
                        pnl=pnl,
                        return_pct=return_pct,
                        direction=pos["direction"],
                        asset=asset,
                    )

                    closed.append({
                        "asset": asset,
                        "pnl": pnl,
                        "reason": close_reason,
                        "strategy": pos["strategy_name"],
                    })

        return closed

    def get_state(self) -> FundState:
        """Get current fund state with verified ledger and health check."""
        peak = max(self.current_capital, self.initial_capital)
        dd = (peak - self.current_capital) / peak if peak > 0 else 0

        is_valid, _ = self.ledger.verify_chain()
        risk_status = self.risk_manager.get_status()

        # Update health monitor with latest state
        self.health_monitor.heartbeat()
        self.health_monitor.update_ledger_status(is_valid)
        self.health_monitor.update_risk_status(risk_status)

        health = self.health_monitor.check_health()

        return FundState(
            capital=self.current_capital,
            peak_capital=peak,
            total_pnl=self.current_capital - self.initial_capital,
            total_return_pct=(self.current_capital / self.initial_capital - 1),
            drawdown_pct=dd,
            open_positions=dict(self.open_positions),
            active_strategies=len(self.active_strategies),
            liquidation_risk_score=0,
            ledger_entries=len(self.ledger.entries),
            ledger_verified=is_valid,
            is_halted=health.should_halt or risk_status.get("is_halted", False),
            halt_reason=health.halt_reason or risk_status.get("halt_reason", ""),
        )

    def get_strategy_attribution(self) -> pd.DataFrame:
        """Performance attribution by strategy — who made/lost money."""
        rows = []
        for name, pnl in self.strategy_pnl.items():
            alloc = self.strategy_allocations.get(name)
            # Get decay report if available
            decay_score = 0.0
            try:
                report = self.decay_detector.check_health(name)
                decay_score = report.decay_score
            except Exception:
                pass

            rows.append({
                "strategy": name,
                "type": alloc.strategy_type if alloc else "unknown",
                "allocation_pct": alloc.allocation_pct if alloc else 0,
                "total_pnl": pnl,
                "pnl_pct": pnl / self.initial_capital if self.initial_capital > 0 else 0,
                "active": alloc.active if alloc else False,
                "decay_score": decay_score,
            })

        df = pd.DataFrame(rows)
        if not df.empty:
            df.sort_values("total_pnl", ascending=False, inplace=True)
        return df

    def get_deep_attribution(self):
        """Full performance attribution via PerformanceEngine.

        Returns portfolio-level report with per-strategy Sharpe,
        bootstrap confidence intervals, factor decomposition, and
        optimal weights.
        """
        return self.performance_engine.portfolio_report()

    def get_health_report(self):
        """Get full system health report."""
        return self.health_monitor.check_health()

    def rebalance_allocations(self):
        """Adjust strategy allocations based on decay detection and performance.

        1. Kill strategies flagged by decay detector
        2. Compute performance attribution
        3. Adjust allocations via momentum-weighted scoring
        """
        if not self.strategy_pnl:
            return

        # 1. Check decay detector — kill dying strategies
        kill_list = self.decay_detector.get_kill_list()
        for name in kill_list:
            alloc = self.strategy_allocations.get(name)
            if alloc and alloc.active:
                alloc.active = False
                self.health_monitor.update_strategy_health(name, "killed_decay")
                logger.warning(f"Killed strategy {name}: decay detector")

        # 2. Log strategy health reports
        for report in self.decay_detector.check_all():
            if report.decay_score > 50 and report.is_alive:
                logger.warning(
                    f"Strategy {report.strategy_name} decay={report.decay_score:.0f}/100"
                )

        # 3. Compute performance scores
        scores = {}
        for name, pnl in self.strategy_pnl.items():
            alloc = self.strategy_allocations.get(name)
            if not alloc or not alloc.active:
                continue
            if name == "liquidation_oracle":
                scores[name] = max(0.1, 1.0 + pnl / max(self.initial_capital * 0.1, 1))
            else:
                scores[name] = max(0.05, 1.0 + pnl / max(self.initial_capital * 0.1, 1))

        total_score = sum(scores.values())
        if total_score <= 0:
            return

        # 4. Normalize and allocate (keep 20% cash buffer)
        available_pct = 0.8
        for name, score in scores.items():
            alloc = self.strategy_allocations.get(name)
            if alloc:
                alloc.allocation_pct = (score / total_score) * available_pct
                # Deactivate strategies that have lost > 5% of initial capital
                if self.strategy_pnl.get(name, 0) < -self.initial_capital * 0.05:
                    alloc.active = False
                    self.health_monitor.update_strategy_health(name, "killed_loss")
                    logger.warning(f"Deactivated strategy {name}: excess losses")

        logger.info("Rebalanced strategy allocations based on performance + decay")
